#!/bin/bash
if [[ ! -e /swiftmq/config/routerconfig.xml ]]; then
   cp /swiftmq/initialconfig/routerconfig.xml /swiftmq/config/.
fi

PWD=`pwd`
cd /swiftmq/optional-swiftlets/extension
for D in */; do
    if [[ ! -e /swiftmq/deploy/${D} ]]; then
        cp -Rf /swiftmq/optional-swiftlets/extension/${D} /swiftmq/deploy/.
    fi
done
cd ${PWD}
keytool -importkeystore -srckeystore $JAVA_HOME/lib/security/cacerts -srcstorepass changeit -destkeystore /swiftmq/certs/client.truststore -deststorepass secret
