#!/bin/bash
if [[ ! -d /swiftmq/data/config ]]; then
   mkdir /swiftmq/data/config
fi
if [[ ! -d /swiftmq/data/preconfig ]]; then
   mkdir /swiftmq/data/preconfig
fi
cp /swiftmq/initialpreconfig/* /swiftmq/data/preconfig/.
if [[ ! -e /swiftmq/data/config/routerconfig.xml ]]; then
   cp /swiftmq/initialconfig/routerconfig.xml /swiftmq/data/config/.
fi
if [[ ! -e /swiftmq/data/deploy ]]; then
   mkdir /swiftmq/data/deploy
fi
if [[ ! -e /swiftmq/data/log ]]; then
   mkdir /swiftmq/data/log
fi

rsync -a /swiftmq/optional-swiftlets/extension/ /swiftmq/data/deploy/
cd /swiftmq/scripts
