#!/bin/bash
ARCH="x64"
if [ `arch` == "x64" ]
then
  ARCH="aarch64"
fi
OSTYPE=`uname | tr "[:upper:]" "[:lower:]"`
EXTRACTED="#GRAALVMRELEASE#"
JAVA_HOME="`pwd`/../${EXTRACTED}"
if [ -d "${JAVA_HOME}" ]
then
  if [ "$1" == "-d" ]
  then
    rm -Rf ${JAVA_HOME}
  else
    echo "${EXTRACTED} is already installed."
    exit -1
  fi
fi
DOWNLOADURL="#GRAALVMURL#.tar.gz"
if [ "${proxyhost}" != "" ] && [ "${proxyport}" != "" ]
then
  echo "Using proxy ${proxyhost}:${proxyport}"
  CURLPROXY="--proxy ${proxyhost}:${proxyport}"
  GUPROXY="--vm.Dhttp.proxyHost=${proxyhost} --vm.Dhttp.proxyPort=${proxyport} --vm.Dhttps.proxyHost=${proxyhost} --vm.Dhttps.proxyPort=${proxyport}"
fi
echo "Installing ${EXTRACTED} ..."
curl ${CURLPROXY} -L -o ../graalvm.tar.gz ${DOWNLOADURL}
tar xf ../graalvm.tar.gz --directory ../
rm -f ../graalvm.tar.gz
EXECUTABLES="${JAVA_HOME}/bin"
if [ "${OSTYPE}" == "darwin" ]
then
  echo "To remove the quarantine attributes from the GraalVM files, please provide your sudo password below (if prompted)."
  sudo xattr -r -d com.apple.quarantine ${JAVA_HOME}
  EXECUTABLES="${JAVA_HOME}/Contents/Home/bin"
fi
echo "The following version of GraalVM has been installed for this SwiftMQ Router:"
${EXECUTABLES}/java -version
echo ${JAVA_HOME} > .javahome
echo ${EXECUTABLES} > .executables
echo "Installation complete."

