#!/bin/bash
JAVAHOME=`java -cp ../jars/swiftmq.jar com.swiftmq.JavaHome`
ISJAVA11=`java -cp ../jars/swiftmq.jar com.swiftmq.IsJava11`
if [ $ISJAVA11 = "false" ]
then
  echo "SwiftMQ requires Java 11 or later installed. Please upgrade your Java installation!"
  exit -1
fi
CLASSP="../jars/swiftmq.jar"
OPENS="--add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED  --add-opens=java.base/sun.net.dns=ALL-UNNAMED -Dnashorn.args=--no-deprecation-warning"
PRECONFIG="-Dswiftmq.preconfig=../data/preconfig/upgrade-to-12.1.0.xml"
if [ "$1" != "" ]
then
  PRECONFIG="$PRECONFIG,$1"
  shift
fi
ROUTEROPT="$OPENS $PRECONFIG -Dswiftmq.directory.autocreate=true -Djavax.net.ssl.keyStore=../certs/server.keystore -Djavax.net.ssl.keyStorePassword=secret -Djavax.net.ssl.trustStore=../certs/client.truststore -Djavax.net.ssl.trustStorePassword=secret"

if [[ ! -e ../certs/.certimported ]]; then
   CACERTS="$JAVAHOME/lib/security/cacerts"
   echo "Import keystore: $CACERTS"
   keytool -importkeystore -srckeystore $CACERTS -srcstorepass changeit -destkeystore ../certs/client.truststore -deststorepass secret  >/dev/null 2>/dev/null
   touch ../certs/.certimported
fi

echo "Starting SwiftMQ. Please have a look at data/log/stdout.log ..."
exec java -server -Xmx2G  $ROUTEROPT -cp $CLASSP com.swiftmq.Router ../data/config/routerconfig.xml >../data/log/stdout.log 2>../data/log/stderr.log
